import type { RecognizedAsset } from "./types"

/**
 * Seed list of globally important assets. Extendable: add an entry here,
 * nothing else needs to change (search integration and lookup both read from
 * this array). Kept as a flat list, not a nested/abstracted structure — per
 * "do not over-engineer," this is a data file, not a framework.
 */
export const RECOGNIZED_ASSETS: RecognizedAsset[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    aliases: ["btc", "xbt"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://blockstream.info",
    websiteUrl: "https://bitcoin.org",
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    aliases: ["eth", "ether"],
    nativeChainId: "ethereum",
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://etherscan.io",
    websiteUrl: "https://ethereum.org",
  },
  {
    id: "bnb",
    name: "BNB",
    symbol: "BNB",
    aliases: ["bnb chain", "binance coin"],
    nativeChainId: "bnb",
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://bscscan.com",
    websiteUrl: "https://www.bnbchain.org",
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    aliases: ["sol"],
    nativeChainId: "solana",
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://solscan.io",
    websiteUrl: "https://solana.com",
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "POL",
    aliases: ["pol", "matic"],
    nativeChainId: "polygon",
    category: "layer2",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://polygonscan.com",
    websiteUrl: "https://polygon.technology",
  },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    aliases: ["avax"],
    nativeChainId: "avalanche",
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://snowtrace.io",
    websiteUrl: "https://www.avax.network",
  },
  {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ARB",
    aliases: ["arb"],
    nativeChainId: "arbitrum",
    category: "layer2",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://arbiscan.io",
    websiteUrl: "https://arbitrum.io",
  },
  {
    id: "optimism",
    name: "Optimism",
    symbol: "OP",
    aliases: ["op"],
    nativeChainId: "optimism",
    category: "layer2",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://optimistic.etherscan.io",
    websiteUrl: "https://www.optimism.io",
  },
  {
    id: "base",
    name: "Base",
    symbol: "BASE",
    aliases: ["base"],
    nativeChainId: "base",
    category: "layer2",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://basescan.org",
    websiteUrl: "https://www.base.org",
  },
  {
    id: "near",
    name: "NEAR Protocol",
    symbol: "NEAR",
    aliases: ["near"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://nearblocks.io",
    websiteUrl: "https://near.org",
  },
  {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    aliases: ["sui"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://suivision.xyz",
    websiteUrl: "https://sui.io",
  },
  {
    id: "aptos",
    name: "Aptos",
    symbol: "APT",
    aliases: ["apt"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://explorer.aptoslabs.com",
    websiteUrl: "https://aptosfoundation.org",
  },
  {
    id: "tron",
    name: "TRON",
    symbol: "TRX",
    aliases: ["trx"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://tronscan.org",
    websiteUrl: "https://tron.network",
  },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    aliases: ["doge"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://blockchair.com/dogecoin",
    websiteUrl: "https://dogecoin.com",
  },
  {
    id: "xrp",
    name: "XRP",
    symbol: "XRP",
    aliases: ["xrp", "ripple"],
    category: "layer1",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://xrpscan.com",
    websiteUrl: "https://xrpl.org",
  },
  {
    id: "chainlink",
    name: "Chainlink",
    symbol: "LINK",
    aliases: ["link"],
    nativeChainId: "ethereum",
    category: "oracle",
    isOfficial: true,
    supportedFeatures: [],
    explorerUrl: "https://etherscan.io",
    websiteUrl: "https://chain.link",
  },
  {
    id: "usdc",
    name: "USD Coin",
    symbol: "USDC",
    aliases: ["usdc", "usd coin"],
    category: "stablecoin",
    isOfficial: true,
    supportedFeatures: [],
    websiteUrl: "https://www.circle.com/usdc",
  },
  {
    id: "usdt",
    name: "Tether",
    symbol: "USDT",
    aliases: ["usdt", "tether"],
    category: "stablecoin",
    isOfficial: true,
    supportedFeatures: [],
    websiteUrl: "https://tether.to",
  },
]
